#ifndef __TUNE_H__
#define __TUNE_H__

#include "player.h"

const byte* Seqs[] = {{}};

const byte SongData0[] = {
LOOP_START, 2, VOLUME, 4, OCTAVE, 4, NOTE_LEN, 29, QUANT_LEN, 29, NOTE_C, NOTE_E, NOTE_G, NOTE_E, NOTE_C, NOTE_E, NOTE_G, NOTE_E, NOTE_C, NOTE_E, NOTE_G, NOTE_E, NOTE_C, NOTE_E, NOTE_G, NOTE_E, NOTE_C, NOTE_E, NOTE_G, NOTE_E, NOTE_C, NOTE_E, NOTE_G, NOTE_E, NOTE_C, NOTE_E, NOTE_A, NOTE_E, NOTE_C, NOTE_E|WITH_LEN|WITH_Q, 30, 29, NOTE_A, NOTE_E, NOTE_C, NOTE_E, NOTE_A, NOTE_E, NOTE_C, NOTE_F, NOTE_A, NOTE_F, NOTE_C, NOTE_F, NOTE_A, NOTE_F, NOTE_C, NOTE_F, NOTE_GS, NOTE_F, NOTE_C, NOTE_F, NOTE_GS, NOTE_F, NOTE_C, NOTE_E, NOTE_G, NOTE_E, NOTE_C, NOTE_E, NOTE_G, NOTE_E|WITH_LEN|WITH_Q, 30, 29, LOOP_END, VOLUME, 3, NOTE_LEN, 59, QUANT_LEN, 59, NOTE_C|WITH_LEN|WITH_Q, 60, 59, END
};
const byte SongData1[] = {
LOOP_START, 2, VOLUME, 4, OCTAVE, 4, NOTE_LEN, 29, QUANT_LEN, 29, NOTE_D, NOTE_C, NOTE_D, NOTE_C, NOTE_D, NOTE_C, NOTE_D, NOTE_C, INC_OCTAVE, NOTE_LEN, 59, QUANT_LEN, 59, NOTE_A, NOTE_G, NOTE_E, NOTE_D, NOTE_C, DEC_OCTAVE, NOTE_A, NOTE_B, INC_OCTAVE, NOTE_C, NOTE_E, REST, NOTE_D|WITH_LEN|WITH_Q, 60, 59, DEC_OCTAVE, NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_C, REST, INC_OCTAVE, NOTE_C, NOTE_D, NOTE_E, NOTE_D, NOTE_C, REST, REST, REST, REST|WITH_LEN|WITH_Q, 60, 59, LOOP_END, END
};
const byte SongData2[] = {
LOOP_START, 2, VOLUME, 14, OCTAVE, 4, NOTE_LEN, 119, QUANT_LEN, 119, NOTE_C, REST, NOTE_C, REST, NOTE_C, REST, DEC_OCTAVE, NOTE_A, REST|WITH_LEN|WITH_Q, 120, 119, NOTE_A, NOTE_F, NOTE_F, NOTE_GS, NOTE_GS, REST, REST|WITH_LEN|WITH_Q, 120, 119, LOOP_END, END
};
const byte SongData3[] = {
LOOP_START, 28, VOLUME, 4, NOTE_LEN, 3, QUANT_LEN, 3, NOTE_C, REST, VOLUME, 2, NOTE_C, REST, VOLUME, 4, NOTE_C|WITH_LEN|WITH_Q, 2, 2, REST, VOLUME, 2, NOTE_C, REST, REST|WITH_LEN|WITH_Q, 2, 2, REST, VOLUME, 4, NOTE_C, REST, VOLUME, 2, NOTE_C|WITH_LEN|WITH_Q, 2, 2, REST, VOLUME, 4, NOTE_C, REST, VOLUME, 6, NOTE_E|WITH_LEN|WITH_Q, 2, 2, REST, VOLUME, 2, NOTE_C, REST, NOTE_LEN, 14, QUANT_LEN, 14, REST, REST, NOTE_LEN, 7, QUANT_LEN, 7, REST|WITH_LEN|WITH_Q, 6, 6, NOTE_G, LOOP_END, END
};
const byte* SongData[] = {SongData0, SongData1, SongData2, SongData3};

#endif /* ifndef __TUNE_H__ */